Use freezed to modeling
GoldenOwlAsia/mobile-flutter-template pull request #3
Opened 2023-04-19 04:22 UTC by go-finn-nguyen

## Refactored model
 - [x] MHandle
 - [x] MResult
 - [x] MPagination
 - [x] MSocialUser
 - [x] MUser

2023-04-21 17:00 UTC, jimmy-to-goldenowl requested changes

2023-04-21 17:00 UTC, jimmy-to-goldenowl commented on lib/src/network/model/common/pagination/pagination.dart
> +  bool get canNext => status.maybeWhen(
bool get canNext {
return hasMore && status is initial or complete
}

2023-04-21 17:00 UTC, jimmy-to-goldenowl commented on lib/src/network/model/common/handle/handle.dart
> +  const factory MHandle.complete(MResult<T> result) = _Complete<T>;
how about error state?

2023-04-21 17:00 UTC, jimmy-to-goldenowl commented on lib/widgets/state/state_widget.dart
> -class XStateWidget extends StatelessWidget {
Could you help to update this file too?

2023-04-24 10:52 UTC, go-finn-nguyen commented on lib/src/network/model/common/handle/handle.dart
> +  const factory MHandle.complete(MResult<T> result) = _Complete<T>;
When an `MHandle` class is completed, it receives an `MResult` as a parameter. `MResult` already has 2 states `MResult.data `& `MResult.error` so we can handle it easily without rewriting them. You can see how it works in [state_widget.dart](lib/widgets/state/state_widget.dart) which I just update.

2023-04-25 06:53 UTC, jimmy-to-goldenowl commented on lib/src/network/model/common/handle/handle.dart
> +  const factory MHandle.complete(MResult<T> result) = _Complete<T>;
I want to add more factory functions. Sometime we not create with MResult. so It is
```
const factory MHandle.initial() = _Initial;
const factory MHandle.loading() = _Loading;
const factory MHandle.success(T data) = _Success<T>;
const factory MHandle.errorr(e) = _Error;
const factory MHandle.result(MResult<T> result) = _Result<T>;
```

2023-04-28 10:04 UTC, jimmy-to-goldenowl commented on lib/src/network/model/common/handle/handle.dart
> +  const factory MHandle.complete(MResult<T> result) = _Complete<T>;
Hi @go-finn-nguyen. I will merge this Pr. Please create another pr for this comment

2023-04-28 10:05 UTC, merged